name: awesome readme

on:
  push:
    branches: [master]

jobs:
  update:
    name: updating...
    runs-on: ubuntu-latest
    steps:
      - name: check it out
        uses: actions/checkout@v2

      - name: do the do do
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_MSHICK }}
        run: ./readme.sh

      - name: great job!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git pull --ff-only && \
          git diff --quiet --exit-code || git commit -am "great job" && \
          git push
